index-web:
  pattern: (?<action>GET) (index)?
  controller: europaphp/main/controller/index

index-cli:
  pattern: (index)?
  controller: europaphp/main/controller/index
  action: cli

module-cli:
  pattern: module
  controller: europaphp/main/controller/module
  action: cli

modules-cli:
  pattern: modules
  controller: europaphp/main/controller/modules
  action: cli
